name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set execute permissions for configure script
      run: chmod +x configure
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: Run make run
      run: make run
